In [55]:
from matplotlib.image import imread
from numpy import array,full,matmul,append,random
from os import listdir as ls
from regex import search
from math import exp
   
class MultilayerPerceptron:
    def __init__(self,hidden_layer,output_layer):
        self.hidden_layer = hidden_layer
        self.output_layer = output_layer
    
    
    def activation_func(self,weight,data):
        net = matmul(data.T,weight)
        return (1-exp(-net))/(1+exp(-net))
    
    def calculate_oh(self,desired,actual):
        return (desired-actual)*(1-actual**2)*.5
    
    def train(self,output_weight,hidden_weight,pattern,label,eta,emax):
        count = 0
        while count<1:
            error = 0
            for j in range(len(pattern)):
                hidden_output = []
                for i in range(self.hidden_layer):
                    
                    out = self.activation_func(hidden_weight[i],pattern[j])
                    hidden_output.append(out)
                hidden_output.append(-1)
                hidden_output = array(hidden_output).reshape(self.hidden_layer+1,1)
                delta_out = array([])
                for i in range(self.output_layer):
#                     print(output_weight[:,i].shape,hidden_output.shape)
                    out = self.activation_func(output_weight[:,i].reshape(len(hidden_output),1),hidden_output)
                    error = error + 0.5*pow((label[j]-out),2)
#                     print(out,label[j])
#                     print(self.calculate_oh(label[j][i],out))
                    delta_out = append(delta_out,self.calculate_oh(label[j][i],out))
#                     print(delta_out)
                delta_out = delta_out.reshape(self.output_layer,1)
                print(delta_out)
                delta_hid = array([])
                for i in range(self.hidden_layer):
                    print(delta_out.shape,output_weight.shape)
                    delta_hid = append(delta_hid,matmul(delta_out.T,output_weight.T[i])*.5*(1-hidden_output[i]**2),axis=0)
                delta_hid = delta_hid.reshape(self.hidden_layer,1)
                output_weight += eta * matmul(delta_out,hidden_output.T)
                x = pattern[j].reshape(1,len(pattern[j]))
                hidden_weight += eta * matmul(delta_hid,x)
                #print(f"y :{hidden_output}")
            count += 1
            print(error)
            if error < emax:
                print(f"cycles completed: {count} \n Hidden layer weights:\n {hidden_weight}\nOutput layer weights: \n{output_weight}\n")
                return


if __name__ == "__main__":
    neuron = MultilayerPerceptron(100,20)    
    hidden = 2*random.random_sample((100,16385))-1
    output = 2*random.random_sample((101,20))-1   
    pattern = array([[0,0,-1],[0,1,-1],[1,0,-1],[1,1,-1]],dtype=float)   
    label = array([0,1,1,0])   
    neuron.train(output,hidden,X_dataset,Y_dataset,1,0.001)


[[-5.65289500e-01]
 [-5.92208356e-01]
 [-8.66359235e-03]
 [-5.58759292e-01]
 [-4.38474711e-04]
 [-6.66062390e-02]
 [-5.17434177e-02]
 [-1.34764569e-08]
 [-2.31247103e-03]
 [ 2.88007938e-05]
 [-9.03551154e-07]
 [-1.00520758e-02]
 [-4.80175395e-03]
 [-5.76416444e-01]
 [-5.59285028e-01]
 [-3.27980216e-06]
 [-1.16549636e-01]
 [-3.83065793e-05]
 [-2.51452962e-01]
 [-5.88486979e-01]]
(20, 1) (101, 20)


ValueError: shapes (1,20) and (101,) not aligned: 20 (dim 1) != 101 (dim 0)

In [10]:
X_dataset = list()
Y_dataset = list()
for img in ls("./coil-20-proc/"):
	im = imread("./coil-20-proc/"+img)
	im = im.reshape(16384)
	im = append(im,-1)    
	X_dataset.append(im)
	result = search('obj(.*?)_', img)
	s=full(20,-1)
	s[int(result[1])-1]=1
	Y_dataset.append(s)
print((X_dataset[0]))
print((Y_dataset[0]))

[ 0.  0.  0. ...  0.  0. -1.]
[-1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [13]:
output = 2*random.random_sample((100,16835))-1
hidden = 2*random.random_sample((101,10))-1